create_ip -name selectio_wiz -vendor xilinx.com -library ip -version 5.1 -module_name SelectIO_frame
set_property -dict [list \
CONFIG.BUS_SIG_TYPE {DIFF} \
CONFIG.BUS_IO_STD {LVDS_25} \
CONFIG.SELIO_ACTIVE_EDGE {DDR} \
CONFIG.USE_SERIALIZATION {true} \
CONFIG.SERIALIZATION_FACTOR {8} \
CONFIG.SELIO_CLK_BUF {MMCM} \
CONFIG.SYSTEM_DATA_WIDTH {1} \
CONFIG.SELIO_INTERFACE_TYPE {NETWORKING} \
CONFIG.SELIO_CLK_IO_STD {HSTL_I} \
CONFIG.CLK_FWD_SIG_TYPE {DIFF} \
CONFIG.CLK_FWD_IO_STD {LVDS_25}] [get_ips SelectIO_frame]

create_ip -name selectio_wiz -vendor xilinx.com -library ip -version 5.1 -module_name SelectIO_valid
set_property -dict [list \
CONFIG.BUS_SIG_TYPE {DIFF} \
CONFIG.BUS_IO_STD {LVDS_25} \
CONFIG.SELIO_ACTIVE_EDGE {DDR} \
CONFIG.USE_SERIALIZATION {true} \
CONFIG.SERIALIZATION_FACTOR {8} \
CONFIG.SELIO_CLK_BUF {MMCM} \
CONFIG.SYSTEM_DATA_WIDTH {1} \
CONFIG.SELIO_INTERFACE_TYPE {NETWORKING} \
CONFIG.SELIO_CLK_IO_STD {HSTL_I} \
CONFIG.CLK_FWD_SIG_TYPE {DIFF} \
CONFIG.CLK_FWD_IO_STD {LVDS_25}] [get_ips SelectIO_valid]

create_ip -name selectio_wiz -vendor xilinx.com -library ip -version 5.1 -module_name SelectIO_data_0
set_property -dict [list \
CONFIG.BUS_SIG_TYPE {DIFF} \
CONFIG.BUS_IO_STD {LVDS_25} \
CONFIG.SELIO_ACTIVE_EDGE {DDR} \
CONFIG.USE_SERIALIZATION {true} \
CONFIG.SERIALIZATION_FACTOR {8} \
CONFIG.SELIO_CLK_BUF {MMCM} \
CONFIG.SYSTEM_DATA_WIDTH {1} \
CONFIG.SELIO_INTERFACE_TYPE {NETWORKING} \
CONFIG.SELIO_CLK_IO_STD {HSTL_I} \
CONFIG.CLK_FWD_SIG_TYPE {DIFF} \
CONFIG.CLK_FWD_IO_STD {LVDS_25}] [get_ips SelectIO_data_0]

create_ip -name selectio_wiz -vendor xilinx.com -library ip -version 5.1 -module_name SelectIO_data_1
set_property -dict [list \
CONFIG.BUS_SIG_TYPE {DIFF} \
CONFIG.BUS_IO_STD {LVDS_25} \
CONFIG.SELIO_ACTIVE_EDGE {DDR} \
CONFIG.USE_SERIALIZATION {true} \
CONFIG.SERIALIZATION_FACTOR {8} \
CONFIG.SELIO_CLK_BUF {MMCM} \
CONFIG.SYSTEM_DATA_WIDTH {1} \
CONFIG.SELIO_INTERFACE_TYPE {NETWORKING} \
CONFIG.SELIO_CLK_IO_STD {HSTL_I} \
CONFIG.CLK_FWD_SIG_TYPE {DIFF} \
CONFIG.CLK_FWD_IO_STD {LVDS_25}] [get_ips SelectIO_data_1]

create_ip -name selectio_wiz -vendor xilinx.com -library ip -version 5.1 -module_name SelectIO_data_2
set_property -dict [list \
CONFIG.BUS_SIG_TYPE {DIFF} \
CONFIG.BUS_IO_STD {LVDS_25} \
CONFIG.SELIO_ACTIVE_EDGE {DDR} \
CONFIG.USE_SERIALIZATION {true} \
CONFIG.SERIALIZATION_FACTOR {8} \
CONFIG.SELIO_CLK_BUF {MMCM} \
CONFIG.SYSTEM_DATA_WIDTH {1} \
CONFIG.SELIO_INTERFACE_TYPE {NETWORKING} \
CONFIG.SELIO_CLK_IO_STD {HSTL_I} \
CONFIG.CLK_FWD_SIG_TYPE {DIFF} \
CONFIG.CLK_FWD_IO_STD {LVDS_25}] [get_ips SelectIO_data_2]

create_ip -name selectio_wiz -vendor xilinx.com -library ip -version 5.1 -module_name SelectIO_data_3
set_property -dict [list \
CONFIG.BUS_SIG_TYPE {DIFF} \
CONFIG.BUS_IO_STD {LVDS_25} \
CONFIG.SELIO_ACTIVE_EDGE {DDR} \
CONFIG.USE_SERIALIZATION {true} \
CONFIG.SERIALIZATION_FACTOR {8} \
CONFIG.SELIO_CLK_BUF {MMCM} \
CONFIG.SYSTEM_DATA_WIDTH {1} \
CONFIG.SELIO_INTERFACE_TYPE {NETWORKING} \
CONFIG.SELIO_CLK_IO_STD {HSTL_I} \
CONFIG.CLK_FWD_SIG_TYPE {DIFF} \
CONFIG.CLK_FWD_IO_STD {LVDS_25}] [get_ips SelectIO_data_3]

create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name PLL_HDMI
set_property -dict [list CONFIG.PRIMITIVE {PLL} \
CONFIG.USE_PHASE_ALIGNMENT {false} \
CONFIG.CLKOUT2_USED {true} \
CONFIG.CLKOUT3_USED {true} \
CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {737.5} \
CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {147.5} \
CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {73.75} \
CONFIG.CLKOUT1_DRIVES {No_buffer} \
CONFIG.PRIM_SOURCE {Single_ended_clock_capable_pin} \
CONFIG.CLKOUT2_DRIVES {BUFG} \
CONFIG.CLKOUT3_DRIVES {BUFG} \
CONFIG.FEEDBACK_SOURCE {FDBK_ONCHIP} \
CONFIG.MMCM_DIVCLK_DIVIDE {4} \
CONFIG.MMCM_BANDWIDTH {OPTIMIZED} \
CONFIG.MMCM_CLKFBOUT_MULT_F {59} \
CONFIG.MMCM_COMPENSATION {ZHOLD} \
CONFIG.MMCM_CLKOUT0_DIVIDE_F {2} \
CONFIG.MMCM_CLKOUT1_DIVIDE {10} \
CONFIG.MMCM_CLKOUT2_DIVIDE {20} \
CONFIG.NUM_OUT_CLKS {3}] [get_ips PLL_HDMI]

create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name MMCM_LVDS
set_property -dict [list \
CONFIG.CLK_IN1_BOARD_INTERFACE {Custom} \
CONFIG.PRIM_SOURCE {Differential_clock_capable_pin} \
CONFIG.PRIM_IN_FREQ {300.000} \
CONFIG.RESET_BOARD_INTERFACE {Custom} \
CONFIG.CLKOUT1_USED {true} \
CONFIG.CLKOUT2_USED {true} \
CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {300.000} \
CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {75.000} \
CONFIG.USE_RESET {false} \
CONFIG.USE_INCLK_STOPPED {true}] [get_ips MMCM_LVDS]

create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name MMCM_DSP
set_property -dict [list \
CONFIG.PRIM_IN_FREQ {100.000} \
CONFIG.CLKOUT1_USED {true} \
CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {100.000} \
CONFIG.USE_RESET {false}] [get_ips MMCM_DSP]

create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ILA_DSP
set_property -dict [list \
CONFIG.C_PROBE2_WIDTH {1} \
CONFIG.C_PROBE1_WIDTH {1} \
CONFIG.C_PROBE0_WIDTH {16} \
CONFIG.C_DATA_DEPTH {16384} \
CONFIG.C_NUM_OF_PROBES {3}] [get_ips ILA_DSP]

create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ILA_FFT
set_property -dict [list \
CONFIG.C_PROBE5_WIDTH {1} \
CONFIG.C_PROBE4_WIDTH {1} \
CONFIG.C_PROBE3_WIDTH {32} \
CONFIG.C_PROBE2_WIDTH {1} \
CONFIG.C_PROBE1_WIDTH {1} \
CONFIG.C_PROBE0_WIDTH {32} \
CONFIG.C_DATA_DEPTH {16384} \
CONFIG.C_NUM_OF_PROBES {6}] [get_ips ILA_FFT]

create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ILA_TRIG
set_property -dict [list \
CONFIG.C_PROBE5_WIDTH {1} \
CONFIG.C_PROBE4_WIDTH {1} \
CONFIG.C_PROBE3_WIDTH {2} \
CONFIG.C_PROBE2_WIDTH {1} \
CONFIG.C_PROBE1_WIDTH {1} \
CONFIG.C_PROBE0_WIDTH {32} \
CONFIG.C_DATA_DEPTH {16384} \
CONFIG.C_NUM_OF_PROBES {6}] [get_ips ILA_TRIG]

# FIFO
create_ip -name axis_data_fifo -vendor xilinx.com -library ip -version 2.0 -module_name AFIFO_0
set_property -dict [list \
CONFIG.TDATA_NUM_BYTES {2} \
CONFIG.FIFO_DEPTH {128} \
CONFIG.IS_ACLK_ASYNC {1}] [get_ips AFIFO_0]

# FIFO
create_ip -name axis_data_fifo -vendor xilinx.com -library ip -version 2.0 -module_name AFIFO_1
set_property -dict [list \
CONFIG.TDATA_NUM_BYTES {2} \
CONFIG.FIFO_DEPTH {128} \
CONFIG.IS_ACLK_ASYNC {1}] [get_ips AFIFO_1]

# FIFO
create_ip -name axis_data_fifo -vendor xilinx.com -library ip -version 2.0 -module_name AFIFO_2
set_property -dict [list \
CONFIG.TDATA_NUM_BYTES {2} \
CONFIG.FIFO_DEPTH {128} \
CONFIG.IS_ACLK_ASYNC {1}] [get_ips AFIFO_2]

# FIFO
create_ip -name axis_data_fifo -vendor xilinx.com -library ip -version 2.0 -module_name AFIFO_3
set_property -dict [list \
CONFIG.TDATA_NUM_BYTES {2} \
CONFIG.FIFO_DEPTH {128} \
CONFIG.IS_ACLK_ASYNC {1}] [get_ips AFIFO_3]

# JTAG to AXI
create_ip -name jtag_axi -vendor xilinx.com -library ip -version 1.2 -module_name JTAG2AXI
set_property -dict [list CONFIG.Component_Name {JTAG2AXI}] [get_ips JTAG2AXI]








###################################################################################
# DDR
###################################################################################
create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo10to10
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {false} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo10to10} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {12} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {1} \
CONFIG.Full_Threshold_Assert_Value {4093} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {4092} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {10} \
CONFIG.Input_Depth {4096} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {10} \
CONFIG.Output_Depth {4096} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {false} \
CONFIG.Read_Data_Count_Width {12} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {true} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {true} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {false} \
CONFIG.Write_Data_Count_Width {12} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo10to10]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo11to11
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {false} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo11to11} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {12} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {true} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {1} \
CONFIG.Full_Threshold_Assert_Value {4093} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {4092} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {11} \
CONFIG.Input_Depth {4096} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {11} \
CONFIG.Output_Depth {4096} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {false} \
CONFIG.Read_Data_Count_Width {12} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {true} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {true} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {false} \
CONFIG.Write_Data_Count_Width {12} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo11to11]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo128to128
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {false} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo128to128} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {11} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {1} \
CONFIG.Full_Threshold_Assert_Value {2045} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {2044} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {128} \
CONFIG.Input_Depth {2048} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {128} \
CONFIG.Output_Depth {2048} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {true} \
CONFIG.Read_Data_Count_Width {11} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {false} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {false} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {false} \
CONFIG.Write_Data_Count_Width {11} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo128to128]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo128to128_2
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {false} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo128to128_2} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {10} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {1} \
CONFIG.Full_Threshold_Assert_Value {1021} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {1020} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {128} \
CONFIG.Input_Depth {1024} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {128} \
CONFIG.Output_Depth {1024} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {Single_Programmable_Full_Threshold_Constant} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {false} \
CONFIG.Read_Data_Count_Width {10} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {true} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {false} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {true} \
CONFIG.Write_Data_Count_Width {10} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo128to128_2]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo128to32
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {false} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo128to32} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {10} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {0} \
CONFIG.Full_Threshold_Assert_Value {1021} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {1020} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {128} \
CONFIG.Input_Depth {1024} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {32} \
CONFIG.Output_Depth {4096} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {Single_Programmable_Full_Threshold_Constant} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {false} \
CONFIG.Read_Data_Count_Width {12} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {true} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {false} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {true} \
CONFIG.Write_Data_Count_Width {10} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo128to32]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo13to13
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {false} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo13to13} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {11} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {1} \
CONFIG.Full_Threshold_Assert_Value {2045} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {2044} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {13} \
CONFIG.Input_Depth {2048} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {13} \
CONFIG.Output_Depth {2048} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {false} \
CONFIG.Read_Data_Count_Width {11} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {false} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {false} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {false} \
CONFIG.Write_Data_Count_Width {11} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo13to13]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo1to1
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {false} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo1to1} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {6} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Distributed_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Distributed_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Distributed_RAM} \
CONFIG.Fifo_Implementation {Common_Clock_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {0} \
CONFIG.Full_Threshold_Assert_Value {62} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {61} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {1} \
CONFIG.Input_Depth {64} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {1} \
CONFIG.Output_Depth {64} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {false} \
CONFIG.Read_Data_Count_Width {6} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {false} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {false} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {false} \
CONFIG.Write_Data_Count_Width {6} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo1to1]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo256to128
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {true} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo256to128} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {10} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {0} \
CONFIG.Full_Threshold_Assert_Value {1021} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {1020} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {256} \
CONFIG.Input_Depth {1024} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {128} \
CONFIG.Output_Depth {2048} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {true} \
CONFIG.Read_Data_Count_Width {11} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {false} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {false} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {false} \
CONFIG.Write_Data_Count_Width {10} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo256to128]

create_ip -name fifo_generator -vendor xilinx.com -library ip -module_name fifo512to128_2
set_property -dict [list \
CONFIG.ADDRESS_WIDTH {32} \
CONFIG.ARUSER_Width {0} \
CONFIG.AWUSER_Width {0} \
CONFIG.Add_NGC_Constraint_AXI {false} \
CONFIG.Almost_Empty_Flag {true} \
CONFIG.Almost_Full_Flag {false} \
CONFIG.BUSER_Width {0} \
CONFIG.C_SELECT_XPM {0} \
CONFIG.Clock_Enable_Type {Slave_Interface_Clock_Enable} \
CONFIG.Clock_Type_AXI {Common_Clock} \
CONFIG.Component_Name {fifo512to128_2} \
CONFIG.DATA_WIDTH {64} \
CONFIG.Data_Count {false} \
CONFIG.Data_Count_Width {11} \
CONFIG.Disable_Timing_Violations {false} \
CONFIG.Disable_Timing_Violations_AXI {false} \
CONFIG.Dout_Reset_Value {0} \
CONFIG.Empty_Threshold_Assert_Value {2} \
CONFIG.Empty_Threshold_Assert_Value_axis {1022} \
CONFIG.Empty_Threshold_Assert_Value_rach {1022} \
CONFIG.Empty_Threshold_Assert_Value_rdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wach {1022} \
CONFIG.Empty_Threshold_Assert_Value_wdch {1022} \
CONFIG.Empty_Threshold_Assert_Value_wrch {1022} \
CONFIG.Empty_Threshold_Negate_Value {3} \
CONFIG.Enable_Common_Overflow {false} \
CONFIG.Enable_Common_Underflow {false} \
CONFIG.Enable_Data_Counts_axis {false} \
CONFIG.Enable_Data_Counts_rach {false} \
CONFIG.Enable_Data_Counts_rdch {false} \
CONFIG.Enable_Data_Counts_wach {false} \
CONFIG.Enable_Data_Counts_wdch {false} \
CONFIG.Enable_Data_Counts_wrch {false} \
CONFIG.Enable_ECC {false} \
CONFIG.Enable_ECC_Type {Hard_ECC} \
CONFIG.Enable_ECC_axis {false} \
CONFIG.Enable_ECC_rach {false} \
CONFIG.Enable_ECC_rdch {false} \
CONFIG.Enable_ECC_wach {false} \
CONFIG.Enable_ECC_wdch {false} \
CONFIG.Enable_ECC_wrch {false} \
CONFIG.Enable_Reset_Synchronization {true} \
CONFIG.Enable_Safety_Circuit {false} \
CONFIG.Enable_TLAST {false} \
CONFIG.Enable_TREADY {true} \
CONFIG.FIFO_Application_Type_axis {Data_FIFO} \
CONFIG.FIFO_Application_Type_rach {Data_FIFO} \
CONFIG.FIFO_Application_Type_rdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wach {Data_FIFO} \
CONFIG.FIFO_Application_Type_wdch {Data_FIFO} \
CONFIG.FIFO_Application_Type_wrch {Data_FIFO} \
CONFIG.FIFO_Implementation_axis {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_rdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wach {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wdch {Common_Clock_Block_RAM} \
CONFIG.FIFO_Implementation_wrch {Common_Clock_Block_RAM} \
CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
CONFIG.Full_Flags_Reset_Value {1} \
CONFIG.Full_Threshold_Assert_Value {2045} \
CONFIG.Full_Threshold_Assert_Value_axis {1023} \
CONFIG.Full_Threshold_Assert_Value_rach {1023} \
CONFIG.Full_Threshold_Assert_Value_rdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wach {1023} \
CONFIG.Full_Threshold_Assert_Value_wdch {1023} \
CONFIG.Full_Threshold_Assert_Value_wrch {1023} \
CONFIG.Full_Threshold_Negate_Value {2044} \
CONFIG.HAS_ACLKEN {false} \
CONFIG.HAS_TKEEP {false} \
CONFIG.HAS_TSTRB {false} \
CONFIG.ID_WIDTH {0} \
CONFIG.INTERFACE_TYPE {Native} \
CONFIG.Inject_Dbit_Error {false} \
CONFIG.Inject_Dbit_Error_axis {false} \
CONFIG.Inject_Dbit_Error_rach {false} \
CONFIG.Inject_Dbit_Error_rdch {false} \
CONFIG.Inject_Dbit_Error_wach {false} \
CONFIG.Inject_Dbit_Error_wdch {false} \
CONFIG.Inject_Dbit_Error_wrch {false} \
CONFIG.Inject_Sbit_Error {false} \
CONFIG.Inject_Sbit_Error_axis {false} \
CONFIG.Inject_Sbit_Error_rach {false} \
CONFIG.Inject_Sbit_Error_rdch {false} \
CONFIG.Inject_Sbit_Error_wach {false} \
CONFIG.Inject_Sbit_Error_wdch {false} \
CONFIG.Inject_Sbit_Error_wrch {false} \
CONFIG.Input_Data_Width {512} \
CONFIG.Input_Depth {2048} \
CONFIG.Input_Depth_axis {1024} \
CONFIG.Input_Depth_rach {16} \
CONFIG.Input_Depth_rdch {1024} \
CONFIG.Input_Depth_wach {16} \
CONFIG.Input_Depth_wdch {1024} \
CONFIG.Input_Depth_wrch {16} \
CONFIG.Master_interface_Clock_enable_memory_mapped {false} \
CONFIG.Output_Data_Width {128} \
CONFIG.Output_Depth {8192} \
CONFIG.Output_Register_Type {Embedded_Reg} \
CONFIG.Overflow_Flag {true} \
CONFIG.Overflow_Flag_AXI {false} \
CONFIG.Overflow_Sense {Active_High} \
CONFIG.Overflow_Sense_AXI {Active_High} \
CONFIG.PROTOCOL {AXI4} \
CONFIG.Performance_Options {Standard_FIFO} \
CONFIG.Programmable_Empty_Type {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_axis {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_rdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wach {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wdch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Empty_Type_wrch {No_Programmable_Empty_Threshold} \
CONFIG.Programmable_Full_Type {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_axis {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_rdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wach {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wdch {No_Programmable_Full_Threshold} \
CONFIG.Programmable_Full_Type_wrch {No_Programmable_Full_Threshold} \
CONFIG.READ_WRITE_MODE {READ_WRITE} \
CONFIG.RUSER_Width {0} \
CONFIG.Read_Clock_Frequency {1} \
CONFIG.Read_Data_Count {true} \
CONFIG.Read_Data_Count_Width {13} \
CONFIG.Register_Slice_Mode_axis {Fully_Registered} \
CONFIG.Register_Slice_Mode_rach {Fully_Registered} \
CONFIG.Register_Slice_Mode_rdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wach {Fully_Registered} \
CONFIG.Register_Slice_Mode_wdch {Fully_Registered} \
CONFIG.Register_Slice_Mode_wrch {Fully_Registered} \
CONFIG.Reset_Pin {true} \
CONFIG.Reset_Type {Asynchronous_Reset} \
CONFIG.Slave_interface_Clock_enable_memory_mapped {false} \
CONFIG.TDATA_NUM_BYTES {1} \
CONFIG.TDEST_WIDTH {0} \
CONFIG.TID_WIDTH {0} \
CONFIG.TKEEP_WIDTH {1} \
CONFIG.TSTRB_WIDTH {1} \
CONFIG.TUSER_WIDTH {4} \
CONFIG.Underflow_Flag {true} \
CONFIG.Underflow_Flag_AXI {false} \
CONFIG.Underflow_Sense {Active_High} \
CONFIG.Underflow_Sense_AXI {Active_High} \
CONFIG.Use_Dout_Reset {true} \
CONFIG.Use_Embedded_Registers {false} \
CONFIG.Use_Embedded_Registers_axis {false} \
CONFIG.Use_Extra_Logic {false} \
CONFIG.Valid_Flag {false} \
CONFIG.Valid_Sense {Active_High} \
CONFIG.WUSER_Width {0} \
CONFIG.Write_Acknowledge_Flag {false} \
CONFIG.Write_Acknowledge_Sense {Active_High} \
CONFIG.Write_Clock_Frequency {1} \
CONFIG.Write_Data_Count {false} \
CONFIG.Write_Data_Count_Width {11} \
CONFIG.asymmetric_port_width {false} \
CONFIG.axis_type {FIFO} \
CONFIG.dynamic_power_saving {false} \
CONFIG.ecc_pipeline_reg {false} \
CONFIG.enable_low_latency {false} \
CONFIG.enable_read_pointer_increment_by2 {false} \
CONFIG.rach_type {FIFO} \
CONFIG.rdch_type {FIFO} \
CONFIG.synchronization_stages {2} \
CONFIG.synchronization_stages_axi {2} \
CONFIG.use_dout_register {false} \
CONFIG.wach_type {FIFO} \
CONFIG.wdch_type {FIFO} \
CONFIG.wrch_type {FIFO} \
] [get_ips fifo512to128_2]

create_ip -name mig_7series -vendor xilinx.com -library ip -module_name mig_7series_1
set_property -dict [list \
CONFIG.BOARD_MIG_PARAM {Custom} \
CONFIG.Component_Name {mig_7series_1} \
CONFIG.MIG_DONT_TOUCH_PARAM {Custom} \
CONFIG.RESET_BOARD_INTERFACE {Custom} \
CONFIG.XML_INPUT_FILE {/home/NikolaPetrovic/Desktop/Doktorat/DISSERTATION_FPGA_150MHz/dissertation/mem_init_files/mig_a.prj} \
] [get_ips mig_7series_1]